# Generated by Django 5.0.7 on 2024-07-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=10, unique=True)),
                ("class_discription", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.BigIntegerField(unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_v1.studentclass",
                    ),
                ),
            ],
        ),
    ]
